TWO_FACTOR_AUTHENTICATION = 'disabled'
SITE_URL = "nhri-hub.com"
SITE_NAME = "demo"
APPLICATION_ID = "https://#{SITE_URL}"
ADMIN_EMAIL = "support@#{SITE_URL}"
NO_REPLY_EMAIL = "no_reply@#{SITE_URL}"
APPLICATION_NAME = "NHRI Hub"
ORGANIZATION_NAME = "Asia Pacific Forum"
CONVENTIONS = {
    "ICERD" => "International Convention on the Elimination of All Forms of Racial Discrimination",
    "ICCPR" => "International Covenant on Civil and Political Rights",
    "ICESCR" => "International Covenant on Economic, Social and Cultural Rights",
    "CEDAW" => "Convention on the Elimination of All Forms of Discrimination against Women",
    "CAT" => "Convention against Torture and Other Cruel, Inhuman or Degrading Treatment or Punishment",
    "CRC" => "Convention on the Rights of the Child",
    "ICMW" => "International Convention on the Protection of the Rights of All Migrant Workers and Members of Their Families",
    "CPED" => "International Convention for the Protection of All Persons from Enforced Disappearance",
    "CRPD" => "Convention on the Rights of Persons with Disabilities"
    }
AGENCIES = {
    "ACC" => "Accident Compensation Corporation",
    "CBS" => "Central Bank",
    "DBS" => "Development Bank ",
    "EPC" => "Electric Power Corporation",
    "FESA" => "Fire and Emergency Services Authority",
    "LTA" => "Land Transport Authority",
    "MAF" => "Ministry of Agriculture and Fisheries",
    "MCIL" => "Ministry of Commerce Industry and Labour",
    "MCIT" => "Ministry of Communications and Information Technology",
    "MESC" => "Ministry of Education, Sports and Culture",
    "MFAT" => "Ministry of Foreign Affairs and Trade",
    "MJCA" => "Ministry of Justice and Courts Administration",
    "MNRE" => "Ministry of Natural Resources and Environment",
    "MOP" => "Minister of Police",
    "MOPPS" => "Ministry of Police and Prisons",
    "MOR" => "Ministry of Revenue",
    "MPE" => "Ministry of Public Enterprises",
    "MPMC" => "Ministry of the Prime Minister and Cabinet",
    "MWCSD" => "Ministry of Women, Community and Social Development",
    "MWTI" => "Ministry of Works, Transport and Infrastructure",
    "MoF" => "Ministry of Finance",
    "MoFA" => "Ministry of Foreign Affairs",
    "MoH" => "Ministry of Health",
    "NHS" => "National Health Service",
    "NUS" => "National University ",
    "PSC" => "Public Services Commission",
    "PTO" => "Public Trust Office",
    "SAA" => "Airport Authority",
    "SAO" => "Audit Office",
    "SBS" => "Bureau of Statistics",
    "SFESA" => "Fire and Emergency Services Authority",
    "SHC" => "Housing Corporateion",
    "SIFA" => "International Finance Authority",
    "SLAC" => "Life Assurance Corporation",
    "SLC" => "Land Corporation",
    "SLRC" => "Law Reform Commission",
    "SNKF" => "National Kidney Foundation",
    "SNPF" => "National Provident Fund",
    "SPA" => "Ports Authority",
    "SQA" => "Qualifications Authority",
    "SROS" => "Scientific Research Organization ",
    "SSC" => "Shipping Corporation",
    "SSFA" => "Sports and Facilities Authority",
    "SSS" => "Shipping Services",
    "STA" => "Tourism Authority",
    "STEC" => "Trust Estates Corporation",
    "SWA" => "Water Authority",
    "UTS" => "Unit Trust "
       }
#       #ComplaintCategories = ["Informal", "Out of Jurisdiction", "Formal"]
AWS_ACCOUNT_ID = "918359762546"
