# for the mailer
TWO_FACTOR_AUTHENTICATION = 'enabled'
SITE_URL = "db.ombudsman.gov.ws"
APPLICATION_ID = "https://#{SITE_URL}"
ADMIN_EMAIL = "support@#{SITE_URL}"
NO_REPLY_EMAIL = "no_reply@#{SITE_URL}"
APPLICATION_NAME = "NHRI Hub"
ORGANIZATION_NAME = "Office of the Ombudsman"
TIME_ZONE = "Pacific Time (US & Canada)"
CONVENTIONS = {
    "ICERD" => "International Convention on the Elimination of All Forms of Racial Discrimination",
    "ICCPR" => "International Covenant on Civil and Political Rights",
    "ICESCR" => "International Covenant on Economic, Social and Cultural Rights",
    "CEDAW" => "Convention on the Elimination of All Forms of Discrimination against Women",
    "CAT" => "Convention against Torture and Other Cruel, Inhuman or Degrading Treatment or Punishment",
    "CRC" => "Convention on the Rights of the Child",
    "ICMW" => "International Convention on the Protection of the Rights of All Migrant Workers and Members of Their Families",
    "CPED" => "International Convention for the Protection of All Persons from Enforced Disappearance",
    "CRPD" => "Convention on the Rights of Persons with Disabilities"
    }
AGENCIES = {
    "ACC" => "Accident Compensation Corporation",
    "LTA" => "Land Transport Authority",
    "MAF" => "Ministry of Agriculture and Fisheries",
    "MCIL" => "Ministry of Commerce Industry and Labour",
    "MCIT" => "Ministry of Communications and Information Technology",
    "MESC" => "Ministry of Education, Sports and Culture",
    "MFAT" => "Ministry of Foreign Affairs and Trade",
    "MJCA" => "Ministry of Justice and Courts Administration",
    "MNRE" => "Ministry of Natural Resources and Environment",
    "MOP" => "Minister of Police",
    "MOR" => "Ministry of Revenue",
    "MPE" => "Ministry of Public Enterprises",
    "MPMC" => "Ministry of the Prime Minister and Cabinet",
    "MoF" => "Ministry of Finance",
    "MoH" => "Ministry of Health",
    "MWCSD" => "Ministry of Women, Community and Social Development",
    "MWTI" => "Ministry of Works, Transport and Infrastructure",
    "SAA" => "Samoa Airport Authority",
    "SFESA" => "Fire and Emergency Services Authority",
    "SNPF" => "Samoa National Provident Fund"
    }
ComplaintCategories = ["Informal", "Out of Jurisdiction", "Formal"]
